import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  GEMINI_A4_RELAYOUT_PROMPT,
  GEMINI_2K_REFINEMENT_PROMPT,
} from '../src/lib/gemini-image-edit.js';

const imagenSource = readFileSync(new URL('../src/lib/imagen.js', import.meta.url), 'utf8');

test('Gemini image generation uses its native portrait aspect-ratio API control', () => {
  assert.match(imagenSource, /export const buildGeminiImageGenerationConfig = \(\{ aspectRatio = "3:4", imageSize \} = \{\}\) =>/);
  assert.match(imagenSource, /aspect_ratio:\s*aspectRatio/);
  assert.match(imagenSource, /mime_type:\s*"image\/jpeg"/);
  assert.match(imagenSource, /\/v1beta\/interactions/);
  assert.match(imagenSource, /response_format:\s*buildGeminiImageGenerationConfig\(imageOptions\)/);
  assert.match(imagenSource, /data\.steps \|\| \[\][\s\S]*part\.type === "image" && part\.data/);
});

test('Gemini manual repair prompts remain provider-specific rather than reusing the ChatGPT copy prompt', () => {
  assert.match(GEMINI_2K_REFINEMENT_PROMPT, /high-resolution 2K refinement/i);
  assert.doesNotMatch(GEMINI_2K_REFINEMENT_PROMPT, /ChatGPT/);
});

test('Gemini layout repair is a provider-specific image-edit instruction', () => {
  assert.match(GEMINI_A4_RELAYOUT_PROMPT, /clean 3:4 portrait canvas/i);
  assert.match(GEMINI_A4_RELAYOUT_PROMPT, /four equal horizontal manga panels/i);
  assert.doesNotMatch(GEMINI_A4_RELAYOUT_PROMPT, /Generated by ChatGPT/);
});

test('Gemini repair remains an external-Web copy workflow and never triggers a hidden API image edit', () => {
  const workflow = readFileSync(new URL('../src/hooks/useMangaWorkflow.js', import.meta.url), 'utf8');
  const step4 = readFileSync(new URL('../src/components/Step4Panel.jsx', import.meta.url), 'utf8');
  assert.doesNotMatch(workflow, /refineGeminiGeneratedImage/);
  assert.match(step4, /Gemini用画像比率修正プロンプトをコピー/);
  assert.match(step4, /Gemini用2K高解像度プロンプトをコピー/);
  assert.match(step4, /navigator\.clipboard\.writeText\(GEMINI_A4_RELAYOUT_PROMPT\)/);
  assert.match(step4, /navigator\.clipboard\.writeText\(GEMINI_2K_REFINEMENT_PROMPT\)/);
  assert.doesNotMatch(step4, /Gemini APIで比率を3:4に再構成/);
  assert.doesNotMatch(step4, /Gemini APIで2K高解像度に再生成/);
});
