import assert from 'node:assert/strict';
import test, { after, before } from 'node:test';
import { createServer } from 'vite';

let server;
let buildMangaPrompt;

before(async () => {
  server = await createServer({
    appType: 'custom',
    logLevel: 'silent',
    server: { middlewareMode: true }
  });
  ({ buildMangaPrompt } = await server.ssrLoadModule('/src/lib/prompt-assembler.js'));
});

after(async () => {
  await server?.close();
});

const CAST_LIST = `
## Hero
- blonde hair, no glasses, warm skin
## Analyst
- dark hair, glasses, pale skin
## Friend
- orange bob hair, no glasses
`;

const SCENARIO = `
## Title: Generic Product Panic!?
Location: supermarket aisle
Outfit: casual clothes

[1コマ目: 起]
[EMOTION: WATERCOLOR]
Action: Hero points at a sealed limited-edition package on a shelf.
Hero「This is exactly the kind of thing that spreads!」

[2コマ目: 承]
[EMOTION: RETRO]
Action: Friend holds the same sealed package while Analyst compares the label.
Friend「Can this really become dessert?」
Analyst「We have to verify the format.」

[3コマ目: 転]
[EMOTION: HORROR]
Action: Analyst tastes a tiny spoonful while Hero records the reaction.
Analyst「My sense of taste is lost.」
Hero「Does this read on camera?」

[4コマ目: 結]
[EMOTION: MONOCHROME_ACCENT]
Action: Friend presents the same package as the only colored object in a monochrome panel.
Friend「This may be the seasonal comic.」
`;

const buildChatGptPrompt = () => buildMangaPrompt({
  scenario: SCENARIO,
  castList: CAST_LIST,
  colorMode: 'color',
  providerFamily: 'chatgpt',
  punchlineType: 'Auto',
  systemVersion: 'v4.8.2-test'
});

const buildGeminiPrompt = () => buildMangaPrompt({
  scenario: SCENARIO,
  castList: CAST_LIST,
  colorMode: 'color',
  providerFamily: 'gemini',
  punchlineType: 'Auto',
  systemVersion: 'v4.8.2-test'
});

test('ChatGPT Web prompt has generic quality locks for dialogue, bubbles, characters, and key props', () => {
  const prompt = buildChatGptPrompt();

  assert.match(prompt, /STRICT SCRIPT LOCK/);
  assert.match(prompt, /Top title EXACTLY "Generic Product Panic!\?"/);
  assert.match(prompt, /KEY PROP \/ OBJECT CONSISTENCY/);
  assert.match(prompt, /DIALOGUE \/ BUBBLE QA LOCK/);
  assert.match(prompt, /CHARACTER QA PASS/);
  assert.match(prompt, /ART-STYLE DIFFERENCE QA LOCK/);
  assert.match(prompt, /Draw in a high-budget, chic and cinematic full-color TV anime style/);
  assert.match(prompt, /official Japanese animation illustration/);
  assert.doesNotMatch(prompt, /Base style: full-color TV anime/);
  assert.match(prompt, /one character, punctuation mark, added word, omitted word, or speaker/i);
  assert.match(prompt, /bubble tail must point to the named speaker/i);
  assert.match(prompt, /hair color, hairstyle, eye color, glasses status, skin tone, outfit/i);
  assert.match(prompt, /at least three of linework, palette, shading, background\/VFX, texture\/surface treatment/i);
  assert.match(prompt, /same clean anime style with only pose, expression, saturation, glow, or speed lines changed/i);
  assert.doesNotMatch(prompt, /canned pudding|bottled drink/i);
});

test('Gemini prompt has stability locks for dialogue duplication, invented cast, and dark-style shadow interpretation', () => {
  const prompt = buildGeminiPrompt();

  assert.match(prompt, /Generated by Gemini with Super FURU AI 4-koma v4\.8\.2-test/);
  assert.match(prompt, /GEMINI STABILITY \/ QUALITY LOCK/);
  assert.match(prompt, /richer professional manga finish than a flat template/i);
  assert.match(prompt, /Do NOT invent a new dominant person, black silhouette, monster, ghost, mascot, presenter, antagonist, or narrator figure/i);
  assert.match(prompt, /draw lighting\/shadow ON that existing named character/i);
  assert.match(prompt, /Do NOT duplicate a line, split one line into repeated bubbles, add new warning phrases, or create extra bubbles/i);
  assert.match(prompt, /Do NOT normalize punctuation/i);
  assert.match(prompt, /Preserve the selected scenario style and each PANEL STYLE LOCK/i);
  assert.doesNotMatch(prompt, /Japanese dialogue MUST end with a period/i);
  assert.doesNotMatch(prompt, /accurately reflect classic anime styles/i);
  assert.doesNotMatch(prompt, /デザイン募集|著作権|クッキー|現金/);
});
