import assert from 'node:assert/strict';
import test, { after, before } from 'node:test';
import { createServer } from 'vite';

let server;
let buildMangaPrompt;

before(async () => {
  server = await createServer({
    appType: 'custom',
    logLevel: 'silent',
    server: { middlewareMode: true }
  });
  ({ buildMangaPrompt } = await server.ssrLoadModule('/src/lib/prompt-assembler.js'));
});

after(async () => {
  await server?.close();
});

const CAST_LIST = `
## ミク
- blonde hair, gyaru, no glasses
## リン
- brown twin tails, glasses
## サエコ
- long black hair
## アカリ
- orange bob hair
## ヒカリ
- short blonde hair, glasses
`;

const SCENARIO = `
## タイトル: 塩ポップコーン論争勃発!?
Location: 映画館ロビー
Outfit: カジュアルな私服

[1コマ目: 起]
[EMOTION: NORMAL]
状況: 映画館ロビーのポップコーン売店前。ミクがキャラメル味を期待している。
ミク「今日は絶対キャラメルっしょ！」

[2コマ目: 承]
[EMOTION: CHIBI_GAG]
状況: 店員が塩味のみ販売の掲示を出し、リンが絶望する。
リン「文明の後退だ…。」

[3コマ目: 転]
[EMOTION: DARK_ANIME]
状況: サエコが規則を宣言し、周囲がざわつく。
サエコ「文句は一切却下します。」

[4コマ目: 結]
[EMOTION: GEKIGA]
状況: ヒカリが静かに次の禁止を想像して全員が凍る。
ヒカリ「次はバター禁止ですか…？」
`;

const buildPrompt = (providerFamily) => buildMangaPrompt({
  scenario: SCENARIO,
  castList: CAST_LIST,
  colorMode: 'color',
  providerFamily,
  punchlineType: 'Auto',
  systemVersion: 'v4.8.2-test'
});

test('ChatGPT-family prompt strictly forbids replacing the scenario story or dialogue', () => {
  const prompt = buildPrompt('chatgpt');
  const scriptLockIndex = prompt.indexOf('STRICT SCRIPT LOCK');
  const panelIndex = prompt.indexOf('PANEL DESCRIPTIONS:');

  assert.ok(scriptLockIndex > -1, 'ChatGPT prompt must include a strict script lock');
  assert.ok(scriptLockIndex < panelIndex, 'script lock must appear before detailed panel descriptions');
  assert.match(prompt, /different story is a failed output/i);
  assert.match(prompt, /Do not replace, rewrite, paraphrase, omit, or add dialogue/i);
  assert.match(prompt, /lower camera, layout, cast-placement, or style instruction conflicts with this script lock/i);
  assert.match(prompt, /Title: 塩ポップコーン論争勃発!\?/);
  assert.match(prompt, /Panel 1 required dialogue: ミク「今日は絶対キャラメルっしょ！」/);
  assert.match(prompt, /Panel 2 required dialogue: リン「文明の後退だ…。」/);
  assert.match(prompt, /Panel 3 required dialogue: サエコ「文句は一切却下します。」/);
  assert.match(prompt, /Panel 4 required dialogue: ヒカリ「次はバター禁止ですか…？」/);
  assert.match(prompt, /Generated by ChatGPT with Super FURU AI 4-koma v4\.8\.2-test/);
});

test('Gemini-family prompt uses the same strict script lock concept without Web API split', () => {
  const prompt = buildPrompt('gemini');
  const scriptLockIndex = prompt.indexOf('STRICT SCRIPT LOCK');
  const panelIndex = prompt.indexOf('PANEL DESCRIPTIONS:');

  assert.ok(scriptLockIndex > -1, 'Gemini prompt must include a strict script lock');
  assert.ok(scriptLockIndex < panelIndex, 'script lock must appear before detailed panel descriptions');
  assert.match(prompt, /different story is a failed output/i);
  assert.match(prompt, /lower camera, layout, cast-placement, or style instruction conflicts with this script lock/i);
  assert.match(prompt, /Panel 1 required dialogue: ミク「今日は絶対キャラメルっしょ！」/);
  assert.match(prompt, /Panel 4 required dialogue: ヒカリ「次はバター禁止ですか…？」/);
  assert.match(prompt, /Generated by Gemini with Super FURU AI 4-koma v4\.8\.2-test/);
  assert.doesNotMatch(prompt, /\b(?:webPrompt|apiPrompt|promptForWeb|promptForApi|chatGPTWeb|openAIAPI|geminiWeb|geminiAPI)\b/i);
});
