import assert from 'node:assert/strict';
import test, { after, before } from 'node:test';
import { createServer } from 'vite';

let server;
let buildMangaPrompt;

before(async () => {
  server = await createServer({
    appType: 'custom',
    logLevel: 'silent',
    server: { middlewareMode: true }
  });
  ({ buildMangaPrompt } = await server.ssrLoadModule('/src/lib/prompt-assembler.js'));
});

after(async () => {
  await server?.close();
});

const CAST_LIST = `
## ミク
- blonde hair, gyaru, no glasses
## リン
- brown twin tails, glasses
## サエコ
- long black hair
## アカリ
- orange bob hair
## ヒカリ
- short blonde hair, glasses
`;

const SCENARIO = `
## タイトル: 塩ポップコーン論争勃発!?
Location: 映画館ロビー
Outfit: カジュアルな私服

[1コマ目: 起]
[EMOTION: NORMAL]
状況: 映画館ロビーのポップコーン売店前。ミクがキャラメル味を期待している。
ミク「今日は絶対キャラメルっしょ！」

[2コマ目: 承]
[EMOTION: CHIBI_GAG]
状況: 店員が塩味のみ販売の掲示を出し、リンが絶望する。
リン「文明の後退だ…。」

[3コマ目: 転]
[EMOTION: DARK_ANIME]
状況: サエコが規則を宣言し、周囲がざわつく。
サエコ「文句は一切却下します。」

[4コマ目: 結]
[EMOTION: GEKIGA]
状況: ヒカリが静かに次の禁止を想像して全員が凍る。
ヒカリ「次はバター禁止ですか…？」
`;

const buildPrompt = (providerFamily) => buildMangaPrompt({
  scenario: SCENARIO,
  castList: CAST_LIST,
  colorMode: 'color',
  providerFamily,
  punchlineType: 'Auto',
  systemVersion: 'v4.8.2-test'
});

test('ChatGPT-family prompt strictly forbids replacing the scenario story or dialogue', () => {
  const prompt = buildPrompt('chatgpt');
  const scriptLockIndex = prompt.indexOf('STRICT SCRIPT LOCK');
  const panelIndex = prompt.indexOf('PANEL DESCRIPTIONS:');

  assert.ok(scriptLockIndex > -1, 'ChatGPT prompt must include a strict script lock');
  assert.ok(scriptLockIndex < panelIndex, 'script lock must appear before detailed panel descriptions');
  assert.match(prompt, /different story is a failed output/i);
  assert.match(prompt, /Do not replace, rewrite, paraphrase, omit, or add dialogue/i);
  assert.match(prompt, /lower camera, layout, cast-placement, or style instruction conflicts with this script lock/i);
  assert.match(prompt, /Title: 塩ポップコーン論争勃発!\?/);
  assert.match(prompt, /Panel 1 required dialogue: ミク「今日は絶対キャラメルっしょ！」/);
  assert.match(prompt, /Panel 2 required dialogue: リン「文明の後退だ…。」/);
  assert.match(prompt, /Panel 3 required dialogue: サエコ「文句は一切却下します。」/);
  assert.match(prompt, /Panel 4 required dialogue: ヒカリ「次はバター禁止ですか…？」/);
  assert.match(prompt, /Generated by ChatGPT with Super FURU AI 4-koma v4\.8\.2-test/);
});

test('Gemini-family prompt uses the same strict script lock concept without Web API split', () => {
  const prompt = buildPrompt('gemini');
  const scriptLockIndex = prompt.indexOf('STRICT SCRIPT LOCK');
  const panelIndex = prompt.indexOf('PANEL DESCRIPTIONS:');

  assert.ok(scriptLockIndex > -1, 'Gemini prompt must include a strict script lock');
  assert.ok(scriptLockIndex < panelIndex, 'script lock must appear before detailed panel descriptions');
  assert.match(prompt, /different story is a failed output/i);
  assert.match(prompt, /lower camera, layout, cast-placement, or style instruction conflicts with this script lock/i);
  assert.match(prompt, /Panel 1 required dialogue: ミク「今日は絶対キャラメルっしょ！」/);
  assert.match(prompt, /Panel 4 required dialogue: ヒカリ「次はバター禁止ですか…？」/);
  assert.match(prompt, /Generated by Gemini with Super FURU AI 4-koma v4\.8\.2-test/);
  assert.doesNotMatch(prompt, /\b(?:webPrompt|apiPrompt|promptForWeb|promptForApi|chatGPTWeb|openAIAPI|geminiWeb|geminiAPI)\b/i);
});

test('keeps quoted ambient sounds out of strict-script dialogue and visual lettering for both providers', () => {
  const ambientSoundScenario = `
## タイトル: 静かな会議!?
Location: 会議室
Outfit: カジュアルな私服

[1コマ目: 起]
状況: ミクが資料を開き、遠くでスプーンの「カチャ」という音。
ミク「確認するよ。」
[2コマ目: 承]
状況: リンが静かにうなずく。
リン「続けて。」
[3コマ目: 転]
状況: サエコが時計を見る。
サエコ「時間ね。」
[4コマ目: 結]
状況: ヒカリが立ち上がり、椅子の軋む「ギシ…」という音。
ヒカリ「終わりました。」
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: ambientSoundScenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'Auto',
      systemVersion: 'v5.0.1-test'
    });

    assert.doesNotMatch(prompt, /カチャ|ギシ/);
    assert.doesNotMatch(prompt, /スプーンの(?:いう|という)音|椅子の軋む(?:いう|という)音/);
    assert.match(prompt, /スプーンの音/);
    assert.match(prompt, /椅子の軋む音/);
    assert.match(prompt, /Panel 1 required dialogue: ミク「確認するよ。」/);
    assert.match(prompt, /Panel 4 required dialogue: ヒカリ「終わりました。」/);
  }
});

test('routes staging-and-gag descriptions to visual action instead of speaker bubbles for both providers', () => {
  const stagingScenario = `
## タイトル: 生成AI観の対立デモ !?
Location: 反AIのデモ会場
Outfit: 反AIメッセージ入りの白いTシャツ

[1コマ目: 起]
演出・ギャグ: 背景に湯気のような熱気の揺らぎ。プラカードの「バンッ」という擬音が小さく浮かぶ。
アカリ「AI反対ーー！！」
ヒカリ「え、えっと…う、うん、そうだよね！」
[2コマ目: 承]
演出・ギャグ: ヒカリの手に汗が滲み、プラカードに「ギュッ」という擬音。プラカード同士が「カサッ」と擦れる音。
ヒカリ「プログラマーは、AI便利って言うけど…！」
リン「こっちは生きるか死ぬかなんだから！」
[3コマ目: 転]
演出・ギャグ: プラカードが振られる「ブンッ」という風切り音。
ミク「AIに私たちの魂まで奪わせるかっての！」
アカリ「私たちの仕事は私たちのものだよ！」
[4コマ目: 結]
全員「AI推進派はいなくなれー！！！」
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: stagingScenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'ドキュメンタリー',
      systemVersion: 'v5.0.3-test'
    });

    assert.doesNotMatch(prompt, /\[演出・ギャグ\]|TAILS[^\n]*演出・ギャグ/);
    assert.doesNotMatch(prompt, /B\d+="(?:背景に湯気|ヒカリの手に汗|プラカードが振られる|ギュッ|カサッ|ブンッ)/);
    assert.doesNotMatch(prompt, /演出・ギャグ\s*[:：]/);
    assert.match(prompt, /「バンッ」という擬音/);
    assert.match(prompt, /「ギュッ」という擬音/);
    assert.match(prompt, /「カサッ」と擦れる音/);
    assert.match(prompt, /「ブンッ」という風切り音/);
    assert.match(prompt, /Panel 1 required dialogue: アカリ「AI反対ーー！！」 \/ ヒカリ「え、えっと…う、うん、そうだよね！」/);
    assert.match(prompt, /Panel 2 required dialogue: ヒカリ「プログラマーは、AI便利って言うけど…！」 \/ リン「こっちは生きるか死ぬかなんだから！」/);
  }
});

test('keeps expression-and-body descriptions with quoted shapes or reactions out of speech bubbles', () => {
  const expressionScenario = `
## タイトル: 米高官「インフレ優先」!?
Location: 国会議事堂の会議室
Outfit: ビジネススーツ

[1コマ目: 起]
状況: ミクが資料を掲げる。
セリフ:
ミク「見て見て！消費税1%下げ案だよ！」

[2コマ目: 承]
状況: ベッセント財務長官が資料を机に叩きつける。
表情・身体: ベッセントは眉を吊り上げ、ミクは目を見開き、アカリの口も「へ」の字で驚き顔。ヒカリはペンを握り直す。
セリフ:
ベッセント「インフレ抑制が最優先だ！」
ヒカリ「減税より…インフレ対策が先なんですか？」

[3コマ目: 転]
状況: サエコがスマホを見せる。
セリフ:
サエコ「Xでは賛否で大荒れよ。」

[4コマ目: 結]
状況: ミクが椅子の上で「インフレもギャルでぶっ飛ばすっしょ！」と絶叫する。
表情・身体: ミクは両手を広げ、アカリはペットボトルを落として「あっ！」と驚いた顔。
セリフ:
ミク「インフレもギャルでぶっとばすっしょ！」
サエコ「ギャル理論で経済回るわけないでしょ！」
ヒカリ「椅子が倒れる…！」
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: expressionScenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'ドキュメンタリー',
      systemVersion: 'v5.1.8-test'
    });

    assert.doesNotMatch(prompt, /表情・身体/);
    assert.doesNotMatch(prompt, /B\d+="(?:ベッセントは眉を吊り上げ|ミクは両手を広げ)/);
    assert.doesNotMatch(prompt, /B\d+="(?:へ|あっ！)"/);
    assert.doesNotMatch(prompt, /Panel 4 required dialogue: ミク「インフレもギャルでぶっ飛ばすっしょ！」/);
    assert.doesNotMatch(prompt, /B\d+="インフレもギャルでぶっ飛ばすっしょ！"/);
    assert.match(prompt, /Panel 2 required dialogue: ベッセント「インフレ抑制が最優先だ！」 \/ ヒカリ「減税より…インフレ対策が先なんですか？」/);
    assert.match(prompt, /Panel 4 required dialogue: ミク「インフレもギャルでぶっとばすっしょ！」 \/ サエコ「ギャル理論で経済回るわけないでしょ！」 \/ ヒカリ「椅子が倒れる…！」/);
    assert.match(prompt, /ベッセントは眉を吊り上げ/);
    assert.match(prompt, /ミクは両手を広げ/);
  }
});

const LONG_DIALOGUE = 'この状況さ、職人がホームセンターの客に「仕事取るな」って怒鳴ってるのと同じだよね…。本気で抗議するなら、店かメーカーに言わない？';
const LONG_DIALOGUE_SCENARIO = `
## タイトル: 長台詞ロック検証!?
Logline: 長い台詞を含む四コマのプロンプト契約を確認する。
Location: 店内
Outfit: カジュアルな私服
Punchline: ドキュメンタリー

[1コマ目: 起]
[EMOTION: NORMAL]
状況: ミクが棚の前で静かに話し始める。
ミク「始めるよ。」

[2コマ目: 承]
[EMOTION: SHADOW]
状況: リンが少し考え込む。
リン「難しいね。」

[3コマ目: 転]
[EMOTION: GEKIGA]
状況: サエコが腕を組む。
サエコ「結論を聞くわ。」

[4コマ目: 結]
[EMOTION: CHIBI_GAG]
状況: ミクが全員を見回して言い切る。
ミク「${LONG_DIALOGUE}」`;

test('keeps long dialogue verbatim inside the highest-priority script lock for both providers', () => {
  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: LONG_DIALOGUE_SCENARIO,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'Auto',
      systemVersion: 'v4.9.9-test'
    });
    const scriptLock = prompt.slice(
      prompt.indexOf('STRICT SCRIPT LOCK'),
      prompt.indexOf('PANEL DESCRIPTIONS:')
    );

    assert.match(scriptLock, new RegExp(`Panel 4 required dialogue: ミク「${LONG_DIALOGUE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}」`));
    assert.doesNotMatch(scriptLock, /EXACT Panel 4 Dialogue below/);
  }
});
