import assert from 'node:assert/strict';
import test, { after, before } from 'node:test';
import { createServer } from 'vite';

let server;
let buildMangaPrompt;

before(async () => {
  server = await createServer({
    appType: 'custom',
    logLevel: 'silent',
    server: { middlewareMode: true }
  });
  ({ buildMangaPrompt } = await server.ssrLoadModule('/src/lib/prompt-assembler.js'));
});

after(async () => {
  await server?.close();
});

const CAST_LIST = `
## ミク
- blonde hair, gyaru, no glasses
## リン
- brown twin tails, glasses
## サエコ
- long black hair
## アカリ
- orange bob hair
## ヒカリ
- short blonde hair, glasses
`;

const SCENARIO = `
## タイトル: 塩ポップコーン論争勃発!?
Location: 映画館ロビー
Outfit: カジュアルな私服

[1コマ目: 起]
[EMOTION: NORMAL]
状況: 映画館ロビーのポップコーン売店前。ミクがキャラメル味を期待している。
ミク「今日は絶対キャラメルっしょ！」

[2コマ目: 承]
[EMOTION: CHIBI_GAG]
状況: 店員が塩味のみ販売の掲示を出し、リンが絶望する。
リン「文明の後退だ…。」

[3コマ目: 転]
[EMOTION: DARK_ANIME]
状況: サエコが規則を宣言し、周囲がざわつく。
サエコ「文句は一切却下します。」

[4コマ目: 結]
[EMOTION: GEKIGA]
状況: ヒカリが静かに次の禁止を想像して全員が凍る。
ヒカリ「次はバター禁止ですか…？」
`;

const buildPrompt = (providerFamily) => buildMangaPrompt({
  scenario: SCENARIO,
  castList: CAST_LIST,
  colorMode: 'color',
  providerFamily,
  punchlineType: 'Auto',
  systemVersion: 'v4.8.2-test'
});

test('ChatGPT-family prompt strictly forbids replacing the scenario story or dialogue', () => {
  const prompt = buildPrompt('chatgpt');
  const scriptLockIndex = prompt.indexOf('STRICT SCRIPT LOCK');
  const panelIndex = prompt.indexOf('PANEL DESCRIPTIONS:');

  assert.ok(scriptLockIndex > -1, 'ChatGPT prompt must include a strict script lock');
  assert.ok(scriptLockIndex < panelIndex, 'script lock must appear before detailed panel descriptions');
  assert.match(prompt, /different story is a failed output/i);
  assert.match(prompt, /Do not replace, rewrite, paraphrase, omit, or add dialogue/i);
  assert.match(prompt, /lower camera, layout, cast-placement, or style instruction conflicts with this script lock/i);
  assert.match(prompt, /Title: 塩ポップコーン論争勃発!\?/);
  assert.match(prompt, /Panel 1 required dialogue: ミク「今日は絶対キャラメルっしょ！」/);
  assert.match(prompt, /Panel 2 required dialogue: リン「文明の後退だ…。」/);
  assert.match(prompt, /Panel 3 required dialogue: サエコ「文句は一切却下します。」/);
  assert.match(prompt, /Panel 4 required dialogue: ヒカリ「次はバター禁止ですか…？」/);
  assert.match(prompt, /Generated by ChatGPT with Super FURU AI 4-koma v4\.8\.2-test/);
});

test('Gemini-family prompt uses the same strict script lock concept without Web API split', () => {
  const prompt = buildPrompt('gemini');
  const scriptLockIndex = prompt.indexOf('STRICT SCRIPT LOCK');
  const panelIndex = prompt.indexOf('PANEL DESCRIPTIONS:');

  assert.ok(scriptLockIndex > -1, 'Gemini prompt must include a strict script lock');
  assert.ok(scriptLockIndex < panelIndex, 'script lock must appear before detailed panel descriptions');
  assert.match(prompt, /different story is a failed output/i);
  assert.match(prompt, /lower camera, layout, cast-placement, or style instruction conflicts with this script lock/i);
  assert.match(prompt, /Panel 1 required dialogue: ミク「今日は絶対キャラメルっしょ！」/);
  assert.match(prompt, /Panel 4 required dialogue: ヒカリ「次はバター禁止ですか…？」/);
  assert.match(prompt, /Generated by Gemini with Super FURU AI 4-koma v4\.8\.2-test/);
  assert.doesNotMatch(prompt, /\b(?:webPrompt|apiPrompt|promptForWeb|promptForApi|chatGPTWeb|openAIAPI|geminiWeb|geminiAPI)\b/i);
});

test('keeps quoted ambient sounds out of strict-script dialogue and visual lettering for both providers', () => {
  const ambientSoundScenario = `
## タイトル: 静かな会議!?
Location: 会議室
Outfit: カジュアルな私服

[1コマ目: 起]
状況: ミクが資料を開き、遠くでスプーンの「カチャ」という音。
ミク「確認するよ。」
[2コマ目: 承]
状況: リンが静かにうなずく。
リン「続けて。」
[3コマ目: 転]
状況: サエコが時計を見る。
サエコ「時間ね。」
[4コマ目: 結]
状況: ヒカリが立ち上がり、椅子の軋む「ギシ…」という音。
ヒカリ「終わりました。」
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: ambientSoundScenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'Auto',
      systemVersion: 'v5.0.1-test'
    });

    assert.doesNotMatch(prompt, /カチャ|ギシ/);
    assert.doesNotMatch(prompt, /スプーンの(?:いう|という)音|椅子の軋む(?:いう|という)音/);
    assert.match(prompt, /スプーンの音/);
    assert.match(prompt, /椅子の軋む音/);
    assert.match(prompt, /Panel 1 required dialogue: ミク「確認するよ。」/);
    assert.match(prompt, /Panel 4 required dialogue: ヒカリ「終わりました。」/);
  }
});

test('routes staging-and-gag descriptions to visual action instead of speaker bubbles for both providers', () => {
  const stagingScenario = `
## タイトル: 生成AI観の対立デモ !?
Location: 反AIのデモ会場
Outfit: 反AIメッセージ入りの白いTシャツ

[1コマ目: 起]
演出・ギャグ: 背景に湯気のような熱気の揺らぎ。プラカードの「バンッ」という擬音が小さく浮かぶ。
アカリ「AI反対ーー！！」
ヒカリ「え、えっと…う、うん、そうだよね！」
[2コマ目: 承]
演出・ギャグ: ヒカリの手に汗が滲み、プラカードに「ギュッ」という擬音。プラカード同士が「カサッ」と擦れる音。
ヒカリ「プログラマーは、AI便利って言うけど…！」
リン「こっちは生きるか死ぬかなんだから！」
[3コマ目: 転]
演出・ギャグ: プラカードが振られる「ブンッ」という風切り音。
ミク「AIに私たちの魂まで奪わせるかっての！」
アカリ「私たちの仕事は私たちのものだよ！」
[4コマ目: 結]
全員「AI推進派はいなくなれー！！！」
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: stagingScenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'ドキュメンタリー',
      systemVersion: 'v5.0.3-test'
    });

    assert.doesNotMatch(prompt, /\[演出・ギャグ\]|TAILS[^\n]*演出・ギャグ/);
    assert.doesNotMatch(prompt, /B\d+="(?:背景に湯気|ヒカリの手に汗|プラカードが振られる|ギュッ|カサッ|ブンッ)/);
    assert.doesNotMatch(prompt, /演出・ギャグ\s*[:：]/);
    assert.match(prompt, /「バンッ」という擬音/);
    assert.match(prompt, /「ギュッ」という擬音/);
    assert.match(prompt, /「カサッ」と擦れる音/);
    assert.match(prompt, /「ブンッ」という風切り音/);
    assert.match(prompt, /Panel 1 required dialogue: アカリ「AI反対ーー！！」 \/ ヒカリ「え、えっと…う、うん、そうだよね！」/);
    assert.match(prompt, /Panel 2 required dialogue: ヒカリ「プログラマーは、AI便利って言うけど…！」 \/ リン「こっちは生きるか死ぬかなんだから！」/);
  }
});

test('routes reversed gag-direction labels to visual action instead of dialogue for both providers', () => {
  const scenario = `
## タイトル: 美術部カノジョ新作話題!?
Location: オタク女子の自宅リビング
Outfit: カジュアルな私服

[1コマ目: 起]
状況: リンがSteamのウィッシュリスト画面を指す。
リン「うちら、これモデルって言われても…否定しきれないよね。」
[2コマ目: 承]
ギャグ演出: 「羞恥」の文字がカナの頭上で赤く点滅、カナは両手をバタバタ。
カナ「この“共感性羞恥”…ガチで心えぐられるやつだよ…！」
[3コマ目: 転]
ギャグ演出: ユリエの目がキラリと光り、背景に「観察中…」の小さな効果音。
ユリエ「私たちの黒歴史、まさかこんな形で…さらされてたのかもね。」
ショウコ「現実にもバグ、普通にいるよね…。」
[4コマ目: 結]
ギャグ演出: ショウコの背後に「バグ多発！」の効果音マーク、リンの頭上に「バグ」の吹き出し、カナの頭上に「現実ショック」のフキダシ。
ショウコ「現実の方が、バグだらけだよ。」
`;
  const castList = `
## リン
- brown hair, twin tails, glasses
## カナ
- orange bob hair
## ユリエ
- blonde hair
## ショウコ
- black hair
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario,
      castList,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'Auto',
      systemVersion: 'v5.1.9-test'
    });

    assert.doesNotMatch(prompt, /B\d+="(?:「羞恥」の文字が|ユリエの目がキラリ|ショウコの背後)/);
    assert.doesNotMatch(prompt, /TAILS[^\n]*ギャグ演出/);
    assert.doesNotMatch(prompt, /ギャグ演出\s*[:：]/);
    assert.match(prompt, /Panel 2 required dialogue: カナ「この“共感性羞恥”…ガチで心えぐられるやつだよ…！」/);
    assert.match(prompt, /Panel 3 required dialogue: ユリエ「私たちの黒歴史、まさかこんな形で…さらされてたのかもね。」 \/ ショウコ「現実にもバグ、普通にいるよね…。」/);
    assert.match(prompt, /Panel 4 required dialogue: ショウコ「現実の方が、バグだらけだよ。」/);
    assert.match(prompt, /「羞恥」の文字がカナの頭上で赤く点滅/);
    assert.match(prompt, /背景に「観察中…」の小さな効果音/);
    assert.match(prompt, /ショウコの背後に「バグ多発！」の効果音マーク/);
  }
});

test('keeps formatted staging-gag label variants visual-only in provider prompts', () => {
  const scenario = `
## タイトル: 美術部カノジョ新作話題!?
Location: オタク女子の自宅リビング
Outfit: カジュアルな私服

[1コマ目: 起]
状況: リンがSteamのウィッシュリスト画面を指す。
リン「うちら、これモデルって言われても…否定しきれないよね。」
[2コマ目: 承]
- ギャグ 演出: 「羞恥」の文字がカナの頭上で赤く点滅、カナは両手をバタバタ。
カナ「この“共感性羞恥”…ガチで心えぐられるやつだよ…！」
[3コマ目: 転]
【演出 / ギャグ： ユリエの目がキラリと光り、背景に「観察中…」の小さな効果音。】
ユリエ「私たちの黒歴史、まさかこんな形で…さらされてたのかもね。」
ショウコ「現実にもバグ、普通にいるよね…。」
[4コマ目: 結]
* ギャグ・演出: ショウコの背後に「バグ多発！」の効果音マーク、リンの頭上に「バグ」の吹き出し、カナの頭上に「現実ショック」のフキダシ。
ショウコ「現実の方が、バグだらけだよ。」
`;
  const castList = `
## リン
- brown hair, twin tails, glasses
## カナ
- orange bob hair
## ユリエ
- blonde wavy hair
## ショウコ
- black hair
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario,
      castList,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'Auto',
      systemVersion: 'v5.1.9-test'
    });

    assert.doesNotMatch(prompt, /B\d+="(?:「羞恥」の文字が|ユリエの目がキラリ|ショウコの背後)/);
    assert.doesNotMatch(prompt, /TAILS[^\n]*(?:ギャグ\s*演出|演出\s*[／/]\s*ギャグ)/);
    assert.doesNotMatch(prompt, /(?:ギャグ\s*(?:[・･／/]\s*)?演出|演出\s*(?:[・･／/]\s*)?ギャグ)\s*[:：]/);
    assert.match(prompt, /Panel 2 required dialogue: カナ「この“共感性羞恥”…ガチで心えぐられるやつだよ…！」/);
    assert.match(prompt, /Panel 3 required dialogue: ユリエ「私たちの黒歴史、まさかこんな形で…さらされてたのかもね。」 \/ ショウコ「現実にもバグ、普通にいるよね…。」/);
    assert.match(prompt, /Panel 4 required dialogue: ショウコ「現実の方が、バグだらけだよ。」/);
    assert.match(prompt, /「羞恥」の文字がカナの頭上で赤く点滅/);
    assert.match(prompt, /背景に「観察中…」の小さな効果音/);
    assert.match(prompt, /ショウコの背後に「バグ多発！」の効果音マーク/);
  }
});

test('keeps expression-and-body descriptions with quoted shapes or reactions out of speech bubbles', () => {
  const expressionScenario = `
## タイトル: 米高官「インフレ優先」!?
Location: 国会議事堂の会議室
Outfit: ビジネススーツ

[1コマ目: 起]
状況: ミクが資料を掲げる。
セリフ:
ミク「見て見て！消費税1%下げ案だよ！」

[2コマ目: 承]
状況: ベッセント財務長官が資料を机に叩きつける。
表情・身体: ベッセントは眉を吊り上げ、ミクは目を見開き、アカリの口も「へ」の字で驚き顔。ヒカリはペンを握り直す。
セリフ:
ベッセント「インフレ抑制が最優先だ！」
ヒカリ「減税より…インフレ対策が先なんですか？」

[3コマ目: 転]
状況: サエコがスマホを見せる。
セリフ:
サエコ「Xでは賛否で大荒れよ。」

[4コマ目: 結]
状況: ミクが椅子の上で「インフレもギャルでぶっ飛ばすっしょ！」と絶叫する。
表情・身体: ミクは両手を広げ、アカリはペットボトルを落として「あっ！」と驚いた顔。
セリフ:
ミク「インフレもギャルでぶっとばすっしょ！」
サエコ「ギャル理論で経済回るわけないでしょ！」
ヒカリ「椅子が倒れる…！」
`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: expressionScenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'ドキュメンタリー',
      systemVersion: 'v5.1.8-test'
    });

    assert.doesNotMatch(prompt, /表情・身体/);
    assert.doesNotMatch(prompt, /B\d+="(?:ベッセントは眉を吊り上げ|ミクは両手を広げ)/);
    assert.doesNotMatch(prompt, /B\d+="(?:へ|あっ！)"/);
    assert.doesNotMatch(prompt, /Panel 4 required dialogue: ミク「インフレもギャルでぶっ飛ばすっしょ！」/);
    assert.doesNotMatch(prompt, /B\d+="インフレもギャルでぶっ飛ばすっしょ！"/);
    assert.match(prompt, /Panel 2 required dialogue: ベッセント「インフレ抑制が最優先だ！」 \/ ヒカリ「減税より…インフレ対策が先なんですか？」/);
    assert.match(prompt, /Panel 4 required dialogue: ミク「インフレもギャルでぶっとばすっしょ！」 \/ サエコ「ギャル理論で経済回るわけないでしょ！」 \/ ヒカリ「椅子が倒れる…！」/);
    assert.match(prompt, /ベッセントは眉を吊り上げ/);
    assert.match(prompt, /ミクは両手を広げ/);
  }
});

test('markdown visual-direction sections never enter strict required dialogue for either provider', () => {
  const scenario = `
## タイトル: 区画テスト!?
Location: 会議室
Outfit: ビジネススーツ

[1コマ目: 起]
状況: ミクが資料を見る。
**表情:**
- ミク：眉をひそめ、口を引き結ぶ。
**セリフ:**
ミク「確認するよ。」

[2コマ目: 承]
状況: アカリが隣から覗き込む。
**表情:**
- アカリ：目をぱちくり、口が小さく「あ」の形。
**身体/間合い:**
- アカリは椅子ごと斜めに寄る。
**セリフ:**
アカリ「まだ出てきそう。」

[3コマ目: 転]
状況: ヒカリが職員証を握る。
**演出:**
- 「ゴー…」という空調音。
**セリフ:**
ヒカリ「話題になってる。」

[4コマ目: 結]
状況: 全員が脱力する。
**表情:**
- ミク：目が半分閉じて、口からため息の「ふー」が出ている。
- リン：点目で無表情、口は一直線。
- ヒカリ：やや頬を膨らませて無言。
**背景:**
- 書棚のファイルに沈黙。
**セリフ:**
アカリ「真面目に生きよう。」`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'ドキュメンタリー',
      systemVersion: 'v5.2.3-test'
    });
    const scriptLock = prompt.slice(
      prompt.indexOf('STRICT SCRIPT LOCK'),
      prompt.indexOf('PANEL DESCRIPTIONS:')
    );

    assert.match(scriptLock, /Panel 2 required dialogue: アカリ「まだ出てきそう。」/);
    assert.match(scriptLock, /Panel 4 required dialogue: アカリ「真面目に生きよう。」/);
    assert.doesNotMatch(scriptLock, /表情「|身体\/間合い「|演出「|背景「|目をぱちくり|目が半分閉じて|点目で無表情|頬を膨らませ|ゴー|ふー/);
    assert.doesNotMatch(prompt, /PLACEMENT\/IDENTITY:[^\n]*(?:\*\*表情|\*\*身体\/間合い|\*\*演出|\*\*背景)/);
  }
});

test('combined visual-direction labels stay out of dialogue and placement for both providers', () => {
  const scenario = `
## タイトル: 複合演出ラベル検証
Location: スーパーマーケット
Outfit: カジュアルな私服

[1コマ目: 起]
状況: 売り場でミクが商品棚を見る。
ミク「新商品だね。」
[2コマ目: 承]
身体・表情・演出: ヒカリは眼鏡を上げ、サエコはPOPを見つめる。効果音「ピシッ」。
ヒカリ「本気なんだ…！」
サエコ「確認するわ。」
[3コマ目: 転]
身体・表情・演出: アカリは顔を紅潮させて両手を広げ、リンはカゴを持ちながら腰が引けている。ミクは額に汗、指を突き出している。「ゴゴゴゴ…」と棚から商品のプレッシャー効果音。
ミク「これヤバい！」
アカリ「もう離れられないっ！」
リン「世界中に広がりそう…！」
[4コマ目: 結]
身体・表情・演出: サエコは口角をわずかに上げ、他のキャラは驚いている。波の中で「ドバーッ！」の効果音。
サエコ「ここが終着駅よ。」`;

  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'ドキュメンタリー',
      systemVersion: 'v5.2.5-test'
    });
    const scriptLock = prompt.slice(
      prompt.indexOf('STRICT SCRIPT LOCK'),
      prompt.indexOf('PANEL DESCRIPTIONS:')
    );

    assert.match(scriptLock, /Panel 3 required dialogue: ミク「これヤバい！」 \/ アカリ「もう離れられないっ！」 \/ リン「世界中に広がりそう…！」/);
    assert.match(prompt, /Action \([^)]*visual[^)]*\):[^\n]*アカリは顔を紅潮させて両手を広げ/i);
    assert.doesNotMatch(scriptLock, /身体・表情・演出「|顔を紅潮|ゴゴゴゴ|ドバーッ/);
    assert.doesNotMatch(prompt, /B\d+="(?:ヒカリは眼鏡を上げ|アカリは顔を紅潮|サエコは口角をわずかに上げ)/);
    assert.doesNotMatch(prompt, /PLACEMENT\/IDENTITY:[^\n]*身体・表情・演出/);
  }
});

const LONG_DIALOGUE = 'この状況さ、職人がホームセンターの客に「仕事取るな」って怒鳴ってるのと同じだよね…。本気で抗議するなら、店かメーカーに言わない？';
const LONG_DIALOGUE_SCENARIO = `
## タイトル: 長台詞ロック検証!?
Logline: 長い台詞を含む四コマのプロンプト契約を確認する。
Location: 店内
Outfit: カジュアルな私服
Punchline: ドキュメンタリー

[1コマ目: 起]
[EMOTION: NORMAL]
状況: ミクが棚の前で静かに話し始める。
ミク「始めるよ。」

[2コマ目: 承]
[EMOTION: SHADOW]
状況: リンが少し考え込む。
リン「難しいね。」

[3コマ目: 転]
[EMOTION: GEKIGA]
状況: サエコが腕を組む。
サエコ「結論を聞くわ。」

[4コマ目: 結]
[EMOTION: CHIBI_GAG]
状況: ミクが全員を見回して言い切る。
ミク「${LONG_DIALOGUE}」`;

test('keeps long dialogue verbatim inside the highest-priority script lock for both providers', () => {
  for (const providerFamily of ['chatgpt', 'gemini']) {
    const prompt = buildMangaPrompt({
      scenario: LONG_DIALOGUE_SCENARIO,
      castList: CAST_LIST,
      colorMode: 'color',
      providerFamily,
      punchlineType: 'Auto',
      systemVersion: 'v4.9.9-test'
    });
    const scriptLock = prompt.slice(
      prompt.indexOf('STRICT SCRIPT LOCK'),
      prompt.indexOf('PANEL DESCRIPTIONS:')
    );

    assert.match(scriptLock, new RegExp(`Panel 4 required dialogue: ミク「${LONG_DIALOGUE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}」`));
    assert.doesNotMatch(scriptLock, /EXACT Panel 4 Dialogue below/);
  }
});
