import assert from 'node:assert/strict';
import test, { after, before } from 'node:test';
import { createServer } from 'vite';

let server;
let buildMangaPrompt;

// Empirical soft budget for manual ChatGPT Web paste.
// This is not an official OpenAI API limit; the API-side hard guard lives in src/lib/openai.js.
const EMPIRICAL_CHATGPT_WEB_COPY_SOFT_BUDGET_CHARS = 15000;

before(async () => {
  server = await createServer({
    appType: 'custom',
    logLevel: 'silent',
    server: { middlewareMode: true }
  });
  ({ buildMangaPrompt } = await server.ssrLoadModule('/src/lib/prompt-assembler.js'));
});

after(async () => {
  await server?.close();
});

const FULL_CAST_LIST = `
- Character [ミク]: female, woman, young adult, medium wavy hair, blonde hair, pink tips, flicked ends, no hairband, tanned skin, no glasses, brown eyes, cheerful, trendy, expressive, gyaru,
- Character [リン]: female, woman, young adult, long twintails, light brown hair, straight hair, blunt bangs, hair ties, glasses, round glasses, pale skin, brown eyes, dreamy, otaku, retro lover, introverted,
- Character [サエコ]: female, woman, young adult, very long straight hair, black hair, natural bangs, no glasses, pale skin, sharp eyes, strict, serious, disciplinary committee, no-nonsense,
- Character [アカリ]: female, woman, young adult, chin-length internal round bob, orange hair, blunt bangs, no hair tie, no glasses, pale skin, brown eyes, cheerful, clumsy, loves sweets, friendly,
- Character [ヒカリ]: female, woman, young adult, chin-length straight bob, blonde hair, blunt bangs, no hair tie, glasses, round glasses, blue eyes, pale skin, bookworm, honor student, shy, caring
`;

const LONG_FOUR_KOMA_SCENARIO = `
## タイトル: 35分長編映像に激辛評価!?
Location: アニメスタジオ
Outfit: アニメの案出家の服装
Punchline: ドキュメンタリー

[1コマ目: 起]
[EMOTION: GLITTER/OVERDRIVE]
[Camera: Hyper Fisheye Swoop（魚眼レンズでミク超ド迫力、机は遠近法で歪む）]
状況: アニメスタジオの巨大な机にミクが原稿を天高く掲げ、顔面フルパワーのドヤ笑顔で目がギラギラ輝く！机に分厚い紙束とペンタブ、机ごとバン！と原稿を全身で叩きつける。その衝撃でアカリとリンが椅子ごと「ズザァァッ！」と後方へ吹っ飛び、机が揺れる。アカリは目玉が飛び出し顎が外れそうなほど絶叫、リンは目をカッと見開いて両手で頭を抱え、髪が総毛立つ。背景はスポットライトがミクを照らし、紙のインクとコーヒーの香りが爆発的に立ちのぼる。
ミク「見てよ！35分フル実写長編できたんだけど！」
アカリ「えっ、それってヤバくない！？」
リン「35分て、映画じゃん！」

[2コマ目: 承]
[EMOTION: GEKIGA/THUNDER]
[Camera: 超ローアングルからサエコを煽る、背後に稲妻エフェクト]
状況: サエコが机の端から身を乗り出し、鋭い目で紙を鬼の形相でバン！と指差す。サエコの背後に黒いオーラと稲妻、口元は鬼のような不敵な笑み。ヒカリは原稿を両手で抱えて硬直、目がグルグルに回り頬が真っ赤、膝がガタガタ震える。舞い上がった紙がスローモーションでひらひら落ち、蛍光灯の光がギラつき、空間を切り裂く心臓の鼓動SFX。
サエコ「ふむ、映像のつながりが破綻してる！」
ヒカリ「キャラの紹介、どこ…？」
ミク「え、そんなにダメ出し！？」

[3コマ目: 転]
[EMOTION: CHIBI_GAG/MELTDOWN]
[Camera: 肩越しアングル＋極端なズームイン、ミク魂抜けアップ]
状況: リンが肩越しに原稿をめくりながら「90秒なら…」「35分は…」と目をギラギラさせてアカリに囁きかけ、アカリは口をへの字にして歯を食いしばりながら「35分は…とても最後まで見られない…」と顔面蒼白で言い放つ。ミクは魂が完全に抜け、椅子から半分滑り落ちた上に顔面真っ青で両手を上げて白旗ポーズ、目は虚ろに半開き。椅子のきしみ音と手汗のベタつき、紙がパラリと床に落ちる音も強調。
リン「90秒なら我慢して見られるよ！」
アカリ「35分は…とても最後まで見られない…」
ミク「ひどいよー…。」

[4コマ目: 結]
[EMOTION: IMPACT/HYPER COMEDY]
[Camera: 超ワイド全景＋ローアングル、爆発エフェクト付き]
状況: スタジオ全景、全員が机の上にペンや資料を「バンバンバンバン！！」と猛烈な勢いで叩きつけ、「今しかない！」の大絶叫がスタジオに轟く。紙が紙吹雪のように宙を舞い、インクの匂いが煙のように立ちこめる。ミクは机の下で仁王立ちし、両拳を高く突き上げて抗議のポーズ、口を「アーーー！」と全開。SFX「ドドドドド！」が爆音で鳴り響き、蛍光灯が点滅、天井から紙切れが降る。全員の表情は形相MAX、アカリは目を血走らせて悪魔のような笑み、リンは歯ぎしりでアゴが割れそう、サエコは鬼の形相で資料を握り潰す。
アカリ「我々の仕事が奪われないうちにこの才能を潰そう！」
リン「御意！」
サエコ「AI作品は無条件で却下よね！」
`;

test('ChatGPT manga prompt stays within the empirical Web-copy soft budget without dropping critical content', () => {
  const prompt = buildMangaPrompt({
    scenario: LONG_FOUR_KOMA_SCENARIO,
    castList: FULL_CAST_LIST,
    colorMode: 'color',
    providerFamily: 'chatgpt',
    punchlineType: 'Documentary',
    systemVersion: 'v4.8.0'
  });

  assert.ok(
    prompt.length <= EMPIRICAL_CHATGPT_WEB_COPY_SOFT_BUDGET_CHARS,
    `expected ChatGPT prompt to stay within the empirical Web-copy soft budget (${EMPIRICAL_CHATGPT_WEB_COPY_SOFT_BUDGET_CHARS.toLocaleString()} chars), got ${prompt.length}`
  );
  assert.equal((prompt.match(/## Panel \d/g) || []).length, 4);
  assert.match(prompt, /35分長編映像に激辛評価!\?/);
  assert.match(prompt, /Generated by ChatGPT with Super FURU AI 4-koma v4\.8\.0/);
  assert.match(prompt, /Speech Bubble 1 \[ミク\]: "見てよ！35分フル実写長編できたんだけど！"/);
  assert.match(prompt, /Speech Bubble 1 \[サエコ\]: "ふむ、映像のつながりが破綻してる！"/);
  assert.doesNotMatch(prompt, /Speech Bubble \d \[リン\]: "90秒なら…"/);
  assert.doesNotMatch(prompt, /Speech Bubble \d \[リン\]: "35分は…"/);
  assert.doesNotMatch(prompt, /Speech Bubble \d: "今しかない！"/);
  assert.match(prompt, /Speech Bubble \d \[リン\]: "90秒なら我慢して見られるよ！"/);
  assert.match(prompt, /Speech Bubble \d \[アカリ\]: "35分は…とても最後まで見られない…"/);
  assert.match(prompt, /Speech Bubble \d \[ミク\]: "ひどいよー…。"/);
  assert.match(prompt, /Speech Bubble \d \[アカリ\]: "我々の仕事が奪われないうちにこの才能を潰そう！"/);
  assert.match(prompt, /Speech Bubble \d \[リン\]: "御意！"/);
  assert.match(prompt, /Speech Bubble \d \[サエコ\]: "AI作品は無条件で却下よね！"/);
  assert.match(prompt, /Dialogue \(verbatim bubbles\):/);
  assert.match(prompt, /vertical Japanese tategaki/i);
  assert.match(prompt, /softening/);
  assert.match(prompt, /synonyms/);
  assert.match(prompt, /MUST HAVE glasses/);
  assert.match(prompt, /MUST NOT have glasses/);
  assert.match(prompt, /THINGS TO AVOID:/);
  assert.match(prompt, /No plastic skin/);
  assert.match(prompt, /extra logos\/watermarks/);
  assert.match(prompt, /floating\/ghost eyes\/faces/);
  assert.match(prompt, /No sparkle\/glow dust/);
  assert.match(prompt, /HAND ANATOMY: correct hands/);
  assert.doesNotMatch(prompt, /NO quotes\/punctuation around title/);
});

const LONG_GEMINI_CAST_LIST = Array.from(
  { length: 5 },
  (_, index) => `- Character [C${index + 1}]: female, woman, young adult, glasses, ${'detailed identity trait '.repeat(160)}, exact long-form marker ${index + 1}`
).join('\n');

const buildLongGeminiBudgetStressScenario = () => {
  const actionBase = '\u80cc\u666f\u51e6\u7406\u3068\u753b\u98a8\u5dee\u3092\u5177\u4f53\u7684\u306b\u6b8b\u3059\u9577\u3044\u8996\u899a\u8aac\u660e\u3002';
  const longAction = `Action: ${actionBase.repeat(120)} STRESS_MARKER_END_GEMINI_BUDGET`;
  return `## \u30bf\u30a4\u30c8\u30eb: \u9577\u6587\u30c6\u30b9\u30c8!?
Location: stadium
Outfit: festival uniform
[1\u30b3\u30de\u76ee: \u8d77]
[EMOTION: RETRO]
C1: \u300c\u4e00\u3064\u76ee\u300d
${longAction}
[2\u30b3\u30de\u76ee: \u627f]
[EMOTION: POP_ART]
C2: \u300c\u4e8c\u3064\u76ee\u300d
${longAction}
[3\u30b3\u30de\u76ee: \u8ee2]
[EMOTION: WATERCOLOR]
C3: \u300c\u4e09\u3064\u76ee\u300d
${longAction}
[4\u30b3\u30de\u76ee: \u7d50]
[EMOTION: SKETCH]
C4: \u300c\u56db\u3064\u76ee\u300d
${longAction}`;
};

test('Gemini manga prompt is not capped by the empirical ChatGPT Web-copy soft budget', () => {
  const prompt = buildMangaPrompt({
    scenario: buildLongGeminiBudgetStressScenario(),
    castList: LONG_GEMINI_CAST_LIST,
    colorMode: 'color',
    providerFamily: 'gemini',
    punchlineType: 'Auto',
    systemVersion: 'v4.8.2-test'
  });

  assert.ok(
    prompt.length > EMPIRICAL_CHATGPT_WEB_COPY_SOFT_BUDGET_CHARS,
    `expected Gemini prompt to be allowed beyond the empirical ChatGPT Web-copy soft budget (${EMPIRICAL_CHATGPT_WEB_COPY_SOFT_BUDGET_CHARS.toLocaleString()} chars), got ${prompt.length}`
  );
  assert.match(prompt, /Generated by Gemini with Super FURU AI 4-koma v4\.8\.2-test/);
  assert.doesNotMatch(prompt, /Generated by ChatGPT/);
  assert.match(prompt, /STRESS_MARKER_END_GEMINI_BUDGET/);
  assert.match(prompt, /PANEL STYLE LOCK: RETRO/);
  assert.match(prompt, /PANEL STYLE LOCK: POP_ART/);
  assert.match(prompt, /PANEL STYLE LOCK: WATERCOLOR/);
  assert.match(prompt, /PANEL STYLE LOCK: SKETCH/);
});
