import assert from 'node:assert/strict';
import test, { before, after } from 'node:test';
import { createServer } from 'vite';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { assertRenderOptions, buildRenderOptionsContract, readRenderOptions } from '../src/lib/render-options.js';

let server, buildMangaPrompt, getScenarioPrompt, qa, compare, repair;
before(async () => {
  server = await createServer({ appType: 'custom', logLevel: 'silent', server: { middlewareMode: true, hmr: false } });
  ({ buildMangaPrompt } = await server.ssrLoadModule('/src/lib/prompt-assembler.js'));
  ({ getScenarioPrompt } = await server.ssrLoadModule('/src/lib/prompts.js'));
  ({ buildImageQualityQaPrompt: qa, buildImageQualityComparisonPrompt: compare } = await server.ssrLoadModule('/src/lib/image-quality-qa.js'));
  ({ buildImageQualityRepairPrompt: repair } = await server.ssrLoadModule('/src/lib/image-quality-failsafe.js'));
});
after(async () => { await server?.close(); });

const castList = '## 葵\n黒髪の成人女性、眼鏡。\n## 凛\n茶髪の成人女性。';
const scenario = `Topic: 展示会の記念写真\nLocation: 展示会\n${[1, 2, 3, 4].map(n => `[${n}コマ目]\n[Camera: ローアングル]\nAction: 葵が凛に本を渡す。凛は本を受け取る。\n葵「記念写真だね」\n凛「よく見えるよ」`).join('\n')}`;
const build = (options = {}) => buildMangaPrompt({ scenario, castList, providerFamily: 'chatgpt', systemVersion: 'test', punchlineType: 'Auto', cinematicTechniques: false, ...options });

test('STEP2 adds the exact mosaic instruction by default and omits it when unchecked', () => {
  const args = { randomCategory: '', targetDate: '2026-09-30', inputMode: 'manual', manualTopic: '展示会で記念撮影', customLocation: '', customOutfit: '', punchlineType: 'Auto' };
  assert.match(getScenarioPrompt(args), /版権キャラクターにおおきなモザイクをかける/);
  assert.doesNotMatch(getScenarioPrompt({ ...args, mosaicCopyrightedCharacters: false }), /版権キャラクターにおおきなモザイクをかける/);
});

for (const providerFamily of ['chatgpt', 'gemini']) {
  for (const colorMode of ['color', 'monochrome']) {
    test(`${providerFamily}/${colorMode}: all checkbox combinations reach the final prompt and QA`, () => {
      for (const mosaicCopyrightedCharacters of [true, false]) for (const showWatermarks of [true, false]) {
        const prompt = build({ providerFamily, colorMode, mosaicCopyrightedCharacters, showWatermarks });
        assert.equal(prompt.includes('版権キャラクターにおおきなモザイクをかける'), mosaicCopyrightedCharacters);
        assert.equal(prompt.includes('ドット絵化ではなく'), mosaicCopyrightedCharacters);
        assert.equal(prompt.includes('特大モザイク'), mosaicCopyrightedCharacters);
        assert.equal(prompt.includes('FINAL MOSAIC OVERRIDE'), providerFamily === 'gemini' && mosaicCopyrightedCharacters);
        if (providerFamily === 'gemini' && mosaicCopyrightedCharacters) {
          assert.match(prompt, /Preserve the scripted subject category, overall silhouette, dominant colors and story role/);
          assert.match(prompt, /Never replace the masked subject with another person, species or object/);
          assert.doesNotMatch(prompt, /takes priority over identity/);
        }
        assert.equal(prompt.includes('目・口・顔の細部を判読できなくする'), mosaicCopyrightedCharacters);
        assert.equal(prompt.includes('https://note.com/happy_duck780'), showWatermarks);
        assert.equal(/(?:Generated by|ChatGPT \/).*FURU AI 4-koma/.test(prompt), showWatermarks);
        for (const review of [qa({ finalPrompt: prompt }), compare({ finalPrompt: prompt })]) {
          assert.equal(review.includes('Pixel-art styling or tiny pixels'), mosaicCopyrightedCharacters);
          assert.equal(review.includes('WATERMARK EDGE CHECK:'), showWatermarks);
          if (mosaicCopyrightedCharacters) assert.match(review, /Intentional mosaic.*not a defect/);
        }
        const repaired = repair({ originalPrompt: prompt, issues: [{ type: 'anatomy', panel: 1, subject: 'hand', reason: 'extra hand' }] });
        assert.equal(repaired.includes('https://note.com/happy_duck780'), showWatermarks);
        assert.equal(repaired.includes('版権キャラクターにおおきなモザイクをかける'), mosaicCopyrightedCharacters);
      }
    });
  }
}

test('defaults preserve both footer credits; unchecked options preserve story text', () => {
  const prompt = build();
  assert.match(prompt, /版権キャラクターにおおきなモザイクをかける/);
  assert.match(prompt, /https:\/\/note.com\/happy_duck780/);
  const off = build({ mosaicCopyrightedCharacters: false, showWatermarks: false });
  assert.match(off, /記念写真だね/);
  assert.match(off, /よく見えるよ/);
  assert.equal((off.match(/^## Panel /gm) || []).length, 4);
  assert.doesNotMatch(off, /both exact watermarks|Keep every watermark glyph|Draw tiny.*watermark/);
});

test('option contract survives long-prompt compaction and cannot be silently removed or changed', () => {
  for (const colorMode of ['color', 'monochrome']) {
    const options = { mosaicCopyrightedCharacters: true, showWatermarks: false };
    const prompt = build({ ...options, colorMode, castList: castList + '\n' + 'original character detail; '.repeat(500) });
    assert.equal(assertRenderOptions(prompt, options), prompt);
    assert.throws(() => assertRenderOptions(prompt, { ...options, showWatermarks: true }), /STEP3/);
    assert.throws(() => assertRenderOptions(prompt.replace(buildRenderOptionsContract(options), ''), options), /STEP3/);
    assert.deepEqual(readRenderOptions(prompt), options);
  }
});

test('both native checkboxes default ON, remain compact, and lock while work is active', async () => {
  const { default: Step2 } = await server.ssrLoadModule('/src/components/Step2Panel.jsx');
  const { default: Step3 } = await server.ssrLoadModule('/src/components/Step3Panel.jsx');
  for (const [Component, label, props, lock] of [
    [Step2, '版権キャラクターにモザイクをかける', { categories: [], targetDate: '2026-09-30', scenario: '', inputMode: 'manual' }, { isRenderOptionsLocked: true }],
    [Step3, 'ウオーターマークを表記する', { currentStep: 3 }, { isColorModeLocked: true }],
  ]) {
    const render = extra => renderToStaticMarkup(React.createElement(Component, { ...props, ...extra }));
    const checkbox = html => html.match(new RegExp('<label[^>]*>\\s*<input type="checkbox"[^>]*>\\s*<span>' + label + '</span>\\s*</label>'))?.[0];
    assert.match(checkbox(render({})), /checked=""/);
    assert.match(checkbox(render({})), /text-xs/);
    assert.match(checkbox(render(lock)), /disabled=""/);
    assert.doesNotMatch(checkbox(render({ mosaicCopyrightedCharacters: false, showWatermarks: false })), /checked=""/);
  }
});

test('actual checkbox handlers invalidate stale output, keep inputs/history and never launch API work', () => {
  const source = readFileSync(new URL('../src/hooks/useMangaWorkflow.js', import.meta.url), 'utf8');
  for (const [name, valueName, invalidator] of [
    ['setMosaicCopyrightedCharacters', 'mosaicCopyrightedCharacters', 'setScenarioFromUser'],
    ['setShowWatermarks', 'showWatermarks', 'invalidateScenarioOutput'],
  ]) {
    const body = source.match(new RegExp(`const ${name} = \\(enabled\\) => \\{([\\s\\S]*?)\\n  \\};`))?.[1];
    assert.ok(body);
    const calls = [];
    const context = { Boolean, isColorModeLocked: false, [valueName]: true, showStatus() {} };
    for (const fn of new Set(body.match(/\b(?:set\w+|invalidateScenarioOutput)(?=\()/g))) context[fn] = value => calls.push([fn, value]);
    vm.runInNewContext(`(enabled => {${body}})(false)`, context);
    assert.ok(calls.some(([fn]) => fn === invalidator));
    assert.ok(calls.some(([fn, value]) => fn === name + 'State' && value === false));
    assert.doesNotMatch(body, /generateScenario\(|assemblePrompt\(|regenerateImage\(|setGenerationHistory\(|setCastList\(|setImages\(|setManualTopic\(/);
    calls.length = 0;
    context.isColorModeLocked = true;
    vm.runInNewContext(`(enabled => {${body}})(false)`, context);
    assert.equal(calls.length, 0);
  }
});
