import * as imageSettings from '../src/lib/openai-image-settings.js';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test, { after, before } from 'node:test';
import { createServer } from 'vite';

let server;
let buildMangaPrompt;

before(async () => {
  server = await createServer({
    appType: 'custom',
    logLevel: 'silent',
    server: { middlewareMode: true },
  });
  ({ buildMangaPrompt } = await server.ssrLoadModule('/src/lib/prompt-assembler.js'));
});

after(async () => {
  await server?.close();
});

const scenario = `Topic: テスト
[1コマ目: 起]
状況: Aが机を見る。
A「始めよう。」
[2コマ目: 承]
状況: Aが考える。
A「なるほど。」
[3コマ目: 転]
状況: Aが驚く。
A「本当？」
[4コマ目: 結]
状況: Aが笑う。
A「できた！」`;

const workflowSource = readFileSync(new URL('../src/hooks/useMangaWorkflow.js', import.meta.url), 'utf8');

test('full-auto keeps STEP 2 model provenance separate from the shared UI model state', () => {
  assert.match(workflowSource, /const scenarioUsedModelRef = useRef\(null\)/);
  assert.match(workflowSource, /scenarioUsedModelRef\.current = result\.usedModel;[\s\S]{0,120}setUsedModel\(result\.usedModel\)/);
  assert.match(workflowSource, /scenarioModelLabel: OPENAI_SCENARIO_MODEL_OPTIONS\.find\(\(\{ id \}\) => id === scenarioUsedModelRef\.current\)\?\.label/);
  assert.doesNotMatch(workflowSource, /scenarioModelLabel: OPENAI_SCENARIO_MODEL_OPTIONS\.find\(\(\{ id \}\) => id === usedModel\)/);
});

test('OpenAI image watermark names the model actually used for the scenario', () => {
  const prompt = buildMangaPrompt({
    scenario,
    castList: 'Character [A]: young adult',
    providerFamily: 'chatgpt',
    colorMode: 'color',
    systemVersion: 'v6.4.2',
    scenarioModelLabel: 'GPT-5.6 Terra',
  });

  assert.match(prompt, /ChatGPT \/ GPT-5\.6 Terra \/ FURU AI 4-koma v6\.4\.2/);
});

test('Gemini watermark remains provider-specific without an OpenAI scenario model', () => {
  const prompt = buildMangaPrompt({
    scenario,
    castList: 'Character [A]: young adult',
    providerFamily: 'gemini',
    colorMode: 'color',
    systemVersion: 'v6.4.2',
  });

  assert.match(prompt, /Generated by Gemini with Super FURU AI 4-koma v6\.4\.2/);
});


test('image engine prefix is added without removing the scenario model', () => {
 const prompt=buildMangaPrompt({scenario,castList:'Character [A]: young adult',providerFamily:'chatgpt',colorMode:'color',systemVersion:'v6.9.6',scenarioModelLabel:'GPT-6.1 Sol',imageEngineLabel:'ChatGPT Images 2.5'});
 assert.ok(prompt.includes('ChatGPT Images 2.5 / GPT-6.1 Sol / FURU AI 4-koma v6.9.6'));
});

test('current image selection updates only the generated footer, preserving dialogue and scenario provenance', () => {
 assert.equal(typeof imageSettings.applyOpenAIImageEngineWatermark,'function');
 const original='- Bottom-right watermark EXACTLY "ChatGPT / GPT-6.1 Sol / FURU AI 4-koma v6.9.6".\nB1="ChatGPT / GPT-6.1 Sol / FURU AI 4-koma v6.9.6"';
 for(const [selection,name] of [['sunburst-max','ChatGPT Images 2.5'],['xhigh','ChatGPT Images 2.5'],['gpt-image-2-high','ChatGPT Images 2.0']]) {
  const updated=imageSettings.applyOpenAIImageEngineWatermark(original,selection);
  assert.ok(updated.split('\n')[0].includes(`${name} / GPT-6.1 Sol / FURU AI 4-koma v6.9.6`));
  assert.equal(updated.split('\n')[1],original.split('\n')[1]);
  assert.equal(imageSettings.applyOpenAIImageEngineWatermark(updated,selection),updated);
 }
 assert.equal(imageSettings.applyOpenAIImageEngineWatermark('B1="ChatGPT"','sunburst-max'),'B1="ChatGPT"');
});
